export default {
    'Attendees: {name}': 'Attendees: {name}',
    'About attendees:': 'About attendees:',
    'Attendees link card aliases (secret tokens) to personal information such as name and email.': 'Attendees link card aliases (secret tokens) to personal information such as name and email.',
    'This allows NFC card holders to place remote orders using their alias without physically scanning their card.': 'This allows NFC card holders to place remote orders using their alias without physically scanning their card.',
    'The alias must remain secret, as it grants access to spend credit from the linked card.': 'The alias must remain secret, as it grants access to spend credit from the linked card.',
    'To actually link a card to an alias, the organiser must check in the attendee using the Check-In module.': 'To actually link a card to an alias, the organiser must check in the attendee using the Check-In module.',
    'Only after check-in is the alias linked to the NFC card.': 'Only after check-in is the alias linked to the NFC card.',
    'Aliases expire after 24 hours.': 'Aliases expire after 24 hours.',
    'Aliases can be generated by external tools such as': 'Aliases can be generated by external tools such as',
    'You can paste tab-separated or colon-separated data directly into the spreadsheet below.': 'You can paste tab-separated or colon-separated data directly into the spreadsheet below.',
    'NFC Card Alias': 'NFC Card Alias',
    'Delete row': 'Delete row',
    'Undo delete': 'Undo delete',
    'Save changes': 'Save changes',
    'Add rows': 'Add rows',
    'Delete all': 'Delete all',
    'Import pasted data': 'Import pasted data',
    'Import': 'Import',
    'First column separator': 'First column separator',
    'Column separator': 'Column separator',
    'Tab': 'Tab',
    'Colon (:)': 'Colon (:)',
    'Semicolon (;)': 'Semicolon (;)',
    'Comma (,)': 'Comma (,)',
    'None (use column separator for all)': 'None (use column separator for all)',
    'Preview': 'Preview',
    '{rows} rows': '{rows} rows',
    'Are you sure you want to delete ALL rows? This cannot be undone after saving.': 'Are you sure you want to delete ALL rows? This cannot be undone after saving.',
    'Approve the public key for device "{name}"? This will allow other terminals to verify cards signed by this device.': 'Approve the public key for device "{name}"? This will allow other terminals to verify cards signed by this device.',
    'Approve the public key for device "{name}"?': 'Approve the public key for device "{name}"?',
    'Revoke the public key for device "{name}"?': 'Revoke the public key for device "{name}"?',
    'Are you sure you want to delete device "{name}"?\n\nThis will revoke the device\'s access token and it will no longer be able to connect. The device will need to be re-paired to use it again.': 'Are you sure you want to delete device "{name}"?\n\nThis will revoke the device\'s access token and it will no longer be able to connect. The device will need to be re-paired to use it again.',
    'Cards signed by {name}:': 'Cards signed by {name}:',
    'Enter license for {name}': 'Enter license for {name}',
    'WARNING: Revoking this key will invalidate {count} cards that were last signed by this device. Are you sure?': 'WARNING: Revoking this key will invalidate {count} cards that were last signed by this device. Are you sure?',
    '⚠️ WARNING: This is a destructive action!\n\nRevoking this key will invalidate {count} cards that were last signed by this device.\n\nAre you absolutely sure?': '⚠️ WARNING: This is a destructive action!\n\nRevoking this key will invalidate {count} cards that were last signed by this device.\n\nAre you absolutely sure?',
    'Balance: {balance}': 'Balance: {balance}',
    '{remaining} of {max} card scans remaining.': '{remaining} of {max} card scans remaining.',
    'Your table number: {tableNumber}': 'Your table number: {tableNumber}',
    'Offline': 'Offline',
    'Device is offline. Remote orders cannot be processed until the connection is restored.': 'Device is offline. Remote orders cannot be processed until the connection is restored.',
    'Sync status': 'Sync status',
    'Last synced:': 'Last synced:',
    'Never': 'Never',
    'Pending transactions:': 'Pending transactions:',
    'These transactions will be uploaded automatically when the connection is restored.': 'These transactions will be uploaded automatically when the connection is restored.',
    'Pending queue items:': 'Pending queue items:',
    'Sync now': 'Sync now',
    'Synchronization complete.': 'Synchronization complete.',
    'There are still {count} pending items that have not been uploaded. Logging out may cause data loss. Are you sure you want to logout?': 'There are still {count} pending items that have not been uploaded. Logging out may cause data loss. Are you sure you want to logout?',

    // NFC Cards
    'Card #{uid}': 'Card #{uid}',
    'Card gives {percentage}% at all sales.': 'Card gives {percentage}% at all sales.',
    'Cards scanned: {scanned} / {max}': 'Cards scanned: {scanned} / {max}',
    'Expires: {date}': 'Expires: {date}',
    'Alias: {alias}': 'Alias: {alias}',
    'Remaining: {remaining}': 'Remaining: {remaining}',

    // Topup
    'Are you sure you want to topup for €{amount}?': 'Are you sure you want to topup for €{amount}?',
    'Amount: {amount}': 'Amount: {amount}',
    'Reason: {reason}': 'Reason: {reason}',

    // Payment Popup
    '{amount} vouchers': '{amount} vouchers',
    'Collect {amount}': 'Collect {amount}',
    'Collect {amount} vouchers': 'Collect {amount} vouchers',

    // Live Sales
    'Total: {amount} items = €{price}': 'Total: {amount} items = €{price}',
    'Total: {total}': 'Total: {total}',

    // Remote Orders
    'Only show "{name}" orders': 'Only show "{name}" orders',
    'Deliver order at table {location}.': 'Deliver order at table {location}.',
    'TABLE {location}': 'TABLE {location}',
    'Order declined. Notify table {location} and ask to enter order again.': 'Order declined. Notify table {location} and ask to enter order again.',
    'Are you sure you want to decline order #{id}?': 'Are you sure you want to decline order #{id}?',
    'Order #{id}': 'Order #{id}',
    'Table: {location}': 'Table: {location}',
    'Client: {requester}': 'Client: {requester}',
    'We have received your order ({orderIds}). Your order is in our queue, we will be there as soon as possible.': 'We have received your order ({orderIds}). Your order is in our queue, we will be there as soon as possible.',

    // Attendees
    'Set attendees {name}': 'Set attendees {name}',

    // Manage - Events
    'Edit event ID#{id}': 'Edit event ID#{id}',

    // Manage - Menu
    'Edit item ID#{id}': 'Edit item ID#{id}',

    // Manage - Devices
    'Are you sure you want to delete device "{name}"?': 'Are you sure you want to delete device "{name}"?',

    // Manage - Payment Gateways
    'Are you sure you want to remove the {gateway} payment gateway?': 'Are you sure you want to remove the {gateway} payment gateway?',
};
